---
name: check_deployment
runner_type: local-shell-script
description: Action which check whether a deployment is running.
enabled: true
entry_point: check_deployment.sh
parameters:
  envname:
    type: "string"
    required: true
    position: 1
#notify:
# on-complete:
#   message: "{{action_context}}"
#   routes:
#     - "slack"
#   data:
#     channel: "{{action_context.message.source_channel}}"